# $schema: values.schema.json
nameOverride: ""

image:
  # -- (string) the image repository
  repository: "docker.io/solidnerd/bookstack"
  # -- (string) the image version
  # @default -- the chart's appVersion
  tag: ""

ingress:
  # -- Whether Ingress object should be included
  enabled: false
  # @schema
  # additionalProperties: true
  # @schema
  # -- (object) extra annotations to add to the ingress object
  # @default -- {}
  annotations: {}
  className: ""
  # -- the hostname for the Ingress
  host: ""

service:
  # -- extra annotations to add to the service object
  annotations:
    foo: bar

deployments: {}
