apiVersion: v2
name: flaresolverr
description: A Helm chart for FlareSolverr
type: application
version: 2.2.2

maintainers:
  - name: somerandow
    email: wojoinc@pm.me
# renovate: datasource=github-releases depName=FlareSolverr/FlareSolverr
appVersion: "v3.4.2"
dependencies:
  - name: common
    version: 0.5.5
    repository: oci://registry.gitlab.com/wojoinc/helm-charts
