apiVersion: v2
name: vaultwarden
description: A Helm chart for deploying vaultwarden
type: application
version: 1.7.1
# renovate: datasource=github-releases depName=dani-garcia/vaultwarden
appVersion: "1.35.2"
maintainers:
  - name: WojoInc
    email: wojoinc@pm.me
dependencies:
  - name: common
    version: 0.4.2
    repository: oci://registry.gitlab.com/wojoinc/helm-charts
  - name: postgresql
    version: 13.4.6
    condition: postgresql.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
